name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:

      - name: Backup .env file
        run: |
          if [ -f backend/.env ]; then
            mkdir -p /tmp/env_backup
            mv backend/.env /tmp/env_backup/
          fi
      - uses: actions/checkout@v4

      - name: Restore .env file
        run: |
          if [ -f /tmp/env_backup/.env ]; then
            mv /tmp/env_backup/.env backend/
          fi
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Build the app
        run: npm run build --if-present
        working-directory: ./backend

      - name: Restart PM2 process
        run: sudo pm2 restart backend
        working-directory: ./backend
